EpamTask/Models/AllModels.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class AllModels 
    {
        public People People { get; set; }
        public Exam Exam { get; set; }
        public Subject Subject { get; set; }
        public ProfessorSubject ProfessorSubject { get; set; }
        
    }
}

EpamTask/Models/Exam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class Exam: IdEntity
    {
        public int StudentId { get; set; }
        public int SubjectId { get; set; }
        public double Grade { get; set; }
    }
}

EpamTask/Models/IdEntity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class IdEntity
    {
        [Key]
        public int Id { get; set; }
    }
}

EpamTask/Models/People.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class People: IdEntity
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public DateTime HireDate { get; set; }
        public DateTime ExamDate { get; set; }   
    }
}

EpamTask/Models/PeopleDbContext.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class PeopleDbContext
    {
        public string GetConnectionString()
        {
            string connectionString = ConfigurationManager.AppSettings["dbConnection"];
            return connectionString;
        }
        
    }
}

EpamTask/Models/ProfessorSubject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class ProfessorSubject: IdEntity
    {
        public int SubjectId { get; set; }
        public string ProfessorInfo { get; set; }     
    }
}

EpamTask/Models/Subject.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpamTask.Models
{
    public class Subject: IdEntity
    {
        public string Title { get; set; }
        public string ShortDescription { get; set; }
  
    }
}

EpamTask/Controllers/ProfessorController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using EpamTask.LogFiles;
using EpamTask.Models;
using EpamTask.Repositories.Implementation;

namespace EpamTask.Controllers
{
    [LoggingFilter]
    public class ProfessorController : Controller
    {
        readonly SubjectRepository _subjectRepository = new SubjectRepository();
        readonly ProfessorRepository _professorRepository = new ProfessorRepository();

        // GET: Professor

        public ActionResult GetSubjectForProfessor()
        {
            ViewBag.Subjects = _subjectRepository.GetAll();
            return View();
        }

        public ActionResult GetAllProfessors()
        {
            ViewBag.AllProfessors = _professorRepository.GetAll();
            return View(ViewBag.AllProfessors);
        }

        // GET: Professor/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {          
            ViewBag.Subject = _subjectRepository.Get(id);
            return View(ViewBag.Subject);
        }
     
        [HttpPost]
        public ActionResult CreateProfessor()
        {
            string info = Request["ProfessorInfo"];
            int Id = Convert.ToInt32(Request["SubjectId"]);
            _professorRepository.Create(info, Id);
           return RedirectToAction("GetAllProfessors");
        }
    }
}

EpamTask/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EpamTask.LogFiles;
using EpamTask.Models;
using EpamTask.Repositories.Implementation;
using NLog;

namespace EpamTask.Controllers
{
    [LoggingFilter]
    public class StudentController : Controller
    {
        readonly StudentRepository _studentRepository = new StudentRepository();
        readonly ExamRepository _examRepository = new ExamRepository();
        readonly AlIExamInfoRepository _allExamInfoRepository = new AlIExamInfoRepository();

        // GET: Student
        public ActionResult Index()
        {
            ViewBag.Students = _studentRepository.GetAll();         
            return View(ViewBag.Students);
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.Det = _studentRepository.Get(id);
            return View(ViewBag.Det);
        }

        public ActionResult GetAllInfoExam(int id)
        {
            ViewBag.ExamInfo = _allExamInfoRepository.Get(id);
            return View(ViewBag.ExamInfo);
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AllModels/Create new Student + Exam + Subject in one query and tie all by id
        [HttpPost]
        public ActionResult Create(AllModels _allModels) 
        {
            try
            {
                _allExamInfoRepository.CreateExam(_allModels);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student's Grade/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
               string grade = Request.Form["Grade"];
                _examRepository.Update(id, grade);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _allExamInfoRepository.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EpamTask/Views/Professor/Details.cshtml
@model EpamTask.Models.Subject

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "GetAllProfessors")
</p>

EpamTask/Views/Professor/GetAllProfessors.cshtml
@model IEnumerable<EpamTask.Models.ProfessorSubject>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubjectId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfessorInfo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfessorInfo)
        </td>
        <td>
           
            @Html.ActionLink("Details", "Details", new { id = item.SubjectId }) 
           
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Come to students list", "Index", "Student", new { id = "" }, null)
</p>

EpamTask/Views/Professor/GetSubjectForProfessor.cshtml
@model IEnumerable<EpamTask.Models.Subject>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br/>
<br/>
    <p>Select the exam for professor:</p>
<select class="form-control" id="ddlSubjects">
    @foreach (var item in ViewBag.Subjects)
    {
        <option value="@item.Id">@item.Title</option>
    }
</select>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("#ddlSubjects").change(function() {
            $(this).find("option:selected").text();
            var selectedValueId = $(this).val();
            document.getElementById('SubjectId').value = selectedValueId;
            document.forms(0).submit();
        });
    });

</script>
<br/>
<form action="/Professor/CreateProfessor" method="post">  
        <hr/>
        <div class="form-group">
            <br/>
            <p>Insert professor information:</p>
            <input class="form-control" type="text" id="ProfessorInfo" name="ProfessorInfo" runat="server" value="">
            <br/>
            <p>Subject id:</p>
            <input class="form-control" type="text" readonly="readonly" id="SubjectId" name="SubjectId" runat="server" value="">
            <br/>
        </div>
    <input type="submit"/>
</form>
<br/>
<br/>
 <p>
    @Html.ActionLink("Come to students list", "Index", "Student", new { id = "" }, null)
</p>  

EpamTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

EpamTask/Views/Student/Create.cshtml
@model EpamTask.Models.AllModels

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add new Student</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.People.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.People.FirstName, new {htmlAttributes = new {@class = "form-control" }})
                @Html.ValidationMessageFor(model => model.People.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>
        @*<div class="form-group">*@
            @Html.LabelFor(model => model.People.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.People.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.People.LastName, "", new {@class = "text-danger"})
            </div>
        @*</div>*@

        @*<div class="form-group">*@
            @Html.LabelFor(model => model.People.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.People.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.People.Description, "", new { @class = "text-danger" })
            </div>
        @*</div>*@
        @*<div class="form-group">*@
            @Html.LabelFor(model => model.People.HireDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.People.HireDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.People.HireDate, "", new {@class = "text-danger"})
            </div>
        @*</div>
        <div class="form-group">*@
            @Html.LabelFor(model => model.People.ExamDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.People.ExamDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.People.ExamDate, "", new {@class = "text-danger"})
            </div>
        @*</div>
        <div class="form-group">*@
            @Html.LabelFor(model => model.Exam.Grade, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exam.Grade, new {htmlAttributes = new {@class = "form-control", @name = "Grade"}})
                @Html.ValidationMessageFor(model => model.Exam.Grade, "", new {@class = "text-danger"})
            </div>
        @*</div>
        <div class="form-group">*@
            @Html.LabelFor(model => model.Subject.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Subject.Title, "", new {@class = "text-danger"})
            </div>
        @*</div>
        <div class="form-group">*@
            @Html.LabelFor(model => model.Subject.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject.ShortDescription, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>   
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EpamTask/Views/Student/Delete.cshtml
@model EpamTask.Models.AllModels

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>AllModels</h4>
        <hr />
        <dl class="dl-horizontal">
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

EpamTask/Views/Student/Details.cshtml
@model EpamTask.Models.People

<div>
    <h4>People</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HireDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExamDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EpamTask/Views/Student/Edit.cshtml
@model EpamTask.Models.Exam

@{
//Layout = null;
        Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Exam</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Grade,  new { htmlAttributes = new { @class = "form-control" , @name = "Grade"} })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

EpamTask/Views/Student/GetAllInfoExam.cshtml
@model EpamTask.Models.AllModels

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetAllInfoExam</title>
</head>
<body>
    <div>
        <h4>AllModels</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.People.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.People.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.People.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.People.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.People.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.People.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.People.HireDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.People.HireDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.People.ExamDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.People.ExamDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Exam.Grade)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Exam.Grade)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Subject.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Subject.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Subject.ShortDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Subject.ShortDescription)
            </dd>
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

EpamTask/Views/Student/Index.cshtml
@model IEnumerable<EpamTask.Models.People>


<br/>
<p>
    @Html.ActionLink("Add New Student", "Create", "Student", new { id = "" }, null)  |
    @Html.ActionLink("Add New Professor", "GetSubjectForProfessor", "Professor", new {id = ""}, null) |
    @Html.ActionLink("Show all professors", "GetAllProfessors", "Professor", new {id = ""}, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>    
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "GetAllInfoExam", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>